### ISSUE TITLE
This is so cool

### ISSUE THREAD

**Issue by greenback-quesq** [lilggamegenius/MDMidi#1]
How about adding in more features such as a MIDI editor?

**Comment by lilggamegenius** [comment]
I could potentially add some small midi editing features to [MID3SMPS](https://github.com/lilggamegenius/MID3SMPS) (since this is just a driver) although I don't plan on adding a full editor, Don't want to bloat the project too much.

**Comment by lilggamegenius** [comment]
I'll go ahead and close this here but feel free to open up an issue on that repo with details on what kind of features you'd want and I'll see what I can do.
